<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerYTC906Z\Glpi_Kernel_KernelProductionContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerYTC906Z/Glpi_Kernel_KernelProductionContainer.php') {
    touch(__DIR__.'/ContainerYTC906Z.legacy');

    return;
}

if (!\class_exists(Glpi_Kernel_KernelProductionContainer::class, false)) {
    \class_alias(\ContainerYTC906Z\Glpi_Kernel_KernelProductionContainer::class, Glpi_Kernel_KernelProductionContainer::class, false);
}

return new \ContainerYTC906Z\Glpi_Kernel_KernelProductionContainer([
    'container.build_hash' => 'YTC906Z',
    'container.build_id' => '57064e0d',
    'container.build_time' => 1780388799,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerYTC906Z');
